config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'subscribe' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'scottsdale-items', to: 'portfolios#scottsdale'
  
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do 
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Mark Morales</span></h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Mark on Rails</h1>
    <p class="lead blog-description">My journey as a Ruby developer</p>
    <span>
      <%= image_tag "blog-banner.jpg", width: 600, class: "blog-banner" %>
    </span>
    <br>
    <br>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path, class: "btn btn-primary" if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path, class: "btn btn-success" %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="
  #navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="container">
    <%= link_to "Mark Morales", root_path, class: "navbar-brand" %>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
  
  
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Sites for Realtors, Bloggers, Musicans, and more!</p>
  </div>
  
  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Check me out here too!</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://www.linkedin.com/in/mark-morales-132961138/"><%=fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <%= link_to "Home", root_path  %>
  <%= link_to "About", about_path %>
  <%= link_to "Contact", contact_path %>
  <%= link_to "Blog", blogs_path %>
  <%= link_to "Portfolio", portfolios_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Images", portfolios_path %> /
      <%= link_to "Create Portfolio item", new_portfolio_path if logged_in?(:site_admin) %>
    </p>
    <p>
    <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Explore My Work</h1>
    <p class="lead text-muted">Take a look at what I've done!
    I'm a very passionate RoR developer. I'm continually learning new technologies and modern solutions is what I use.
    I believe a good modern approach is what helps bring in the right clientele. </p>
      <%= link_to 'About Mark Morales', about_path, class: 'btn btn-primary' %>
      <%= link_to 'Mark on Rails Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About Me</h4>
        <p class="text-muted">"Glass House development" is what I do. I give you consistent updates on the progress of your site.
        You will never feel "locked out" of the process.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Discover</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Mark Morales", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>